## Библиотека `NumPy`

* Дан массив, содержащий баллы слушателей курса по английскому языку за вступительный экзамен. 
* Слушатели распределены по 15 группам по 10 человек.

In [1]:
import numpy as np

scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])


### Задание 1

Посчитать, сколько слушателей получили 0 за вступительный экзамен.

In [2]:
losers = scores <= 0
losers.sum()

13

### Задание 2

Посчитать, сколько слушателей получили балл выше 50.

In [3]:
excellent = scores > 50
excellent.sum()

64

### Задание 3

Посчитать, сколько человек получили балл не ниже 50, но не выше 70.

In [4]:
good = (scores >= 50) & (scores <= 70)
good.sum()

26

### Задание 4

Определить, в какой группе средний балл за вступительный экзамен выше.

In [5]:
middle = scores.mean(axis = 1)
print(middle)
print(middle.max())
middle.argmax()

[32.8 55.2 55.4 55.3 50.8 35.7 53.4 47.5 37.6 57.9 26.  55.2 31.6 57.4
 40.1]
57.9


9

### Задание 5

Сохранить баллы слушателей выше 0 в массив `nonzero`. 

In [6]:
nonzero = scores[scores > 0]
nonzero

array([ 20,  40,  56,  80,   5,  25,  27,  74,   1,  98,  67, 100,   8,
        56,  34,  82, 100,   7,  78,  54,  23,  79, 100,  42,  95,  83,
        51,  50,  47,  23, 100,  94,  25,  48,  38,  77,  90,  87,  41,
        89,  52,   5,  17,  28,  99,  32,  18,  21,  18,  29,  31,  48,
        62,  76,  22,   6,  65,  78,  43,  22,  38,  88,  94, 100,  77,
        28,  39,  41,  81,  45,  54,  98,  12,  66,  88,  44,  55, 100,
        12,  11,  17,  70,  86,  96,  56,  23,  32,  49,  70,  80,  20,
        24,  76,  50,  29,  40,   3,   2,   5,  11,  33,  63,  28,  40,
        51, 100,  98,  87,  22,  30,  16,  54,  78,  12,  25,  35,  10,
        19,  67, 100,  88,  24,  33,  47,  56,  62,  34,  77,  53,  50,
        89,  70,  72,  56,  29,  15,  20])

### Задание 6

Используя массив `nonzero`, определить минимальный балл за вступительный балл по всем группам.

In [7]:
nonzero.min()

1

### Задание 7

* Выбрать из массива `nonzero` только те значения, которые соответствуют продвинутому уровню знания языка – баллу за экзамен выше 80. 
* Сохранить полученный результат в массив `advanced`. 
* В заданиях 8-10 нужно работать с массивом `advanced`.

In [8]:
advanced = nonzero[nonzero > 80]
advanced

array([ 98, 100,  82, 100, 100,  95,  83, 100,  94,  90,  87,  89,  99,
        88,  94, 100,  81,  98,  88, 100,  86,  96, 100,  98,  87, 100,
        88,  89])

### Задание 8

Определить размерность массива `advanced`.

In [9]:
advanced.ndim

1

### Задание 9

Определить форму массива `advanced`.

In [10]:
advanced.shape

(28,)

### Задание 10

Определить общее число элементов в массиве `advanced`.

In [11]:
advanced.size

28

### Задание 11

На основе исходного массива `scores` создать булев массив `sto`, где `True` соответствует баллам за экзамен, равным 100, а `False` – всем остальным баллам. 

In [12]:
sto = scores == 100
sto

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True, False, False, False, False,  True,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False,  True, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, 

### Задание 12

На основе исходного массива `scores` вывести на экран оценки слушателей первых семи групп (включительно, должны быть 7 списков оценок).

In [13]:
scores[:7]

array([[ 20,  40,  56,  80,   0,   5,  25,  27,  74,   1],
       [  0,  98,  67, 100,   8,  56,  34,  82, 100,   7],
       [ 78,  54,  23,  79, 100,   0,   0,  42,  95,  83],
       [ 51,  50,  47,  23, 100,  94,  25,  48,  38,  77],
       [ 90,  87,  41,  89,  52,   0,   5,  17,  28,  99],
       [ 32,  18,  21,  18,  29,  31,  48,  62,  76,  22],
       [  6,   0,  65,  78,  43,  22,  38,  88,  94, 100]])

### В заданиях 13-14 необходимо работать с массивом `A`:

In [14]:
A = np.array([[2, 9, 8, 0],
             [8, 7, 5, 6], 
             [3, 1, 0, 2], 
             [6, 5, 6, 8],
             [1, 0, 0, 4]])

### Задание 13

* Транспонировать массив `A`, не используя встроенных методов `NumPy`. 
* Сохранить полученный массив в переменную `A_tr`. 
* Допустимо использовать циклы и условные конструкции (при необходимости).

In [15]:
m = [[2, 9, 8, 0], [8, 7, 5, 6], [3, 1, 0, 2], [6, 5, 6, 8], [1, 0, 0, 4]]
for row in m:
    print(row)
A_tr = [[m[j][i] for j in range(len(m))] for i in range(len(m[0]))] 

# перебираем каждый элемент матрицы (m) в основном столбце
# и присваиваем результат матрице A_tr, которая является транспозицией m

print("\n") 
for row in A_tr: 
    print(row)             

[2, 9, 8, 0]
[8, 7, 5, 6]
[3, 1, 0, 2]
[6, 5, 6, 8]
[1, 0, 0, 4]


[2, 8, 3, 6, 1]
[9, 7, 1, 5, 0]
[8, 5, 0, 6, 0]
[0, 6, 2, 8, 4]


### Задание 14

Сравнить результаты: проверить равенство полученного выше массива `A_tr` и массива, который получается транспонированием массива `A` с помощью метода `.T`. 

In [16]:
print(A.T)
np.array_equal(A_tr, A.T)

[[2 8 3 6 1]
 [9 7 1 5 0]
 [8 5 0 6 0]
 [0 6 2 8 4]]


True

### Задание 15

* Студент N подрабатывает репетитором по математике и ведёт занятия разных типов: готовит к ЕГЭ, к олимпиадам, «подтягивает» математику у школьников младших классов. 
* В массиве `classes` хранится число проведённых уроков за пять рабочих дней, в массиве `prices` — стоимость одного урока (считаем, что студент за день проводит занятия одного типа, одинаковые по стоимости).
* Определить доход студента за неделю, используя [метод](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) `.dot()` для нахождения [скалярного произведения](https://ru.wikipedia.org/wiki/%D0%A1%D0%BA%D0%B0%D0%BB%D1%8F%D1%80%D0%BD%D0%BE%D0%B5_%D0%BF%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5). 

In [17]:
classes = np.array([3, 3, 2, 0, 2])
prices = np.array([1500, 1500, 2500, 1000, 1000])

In [18]:
np.dot(classes, prices)

16000

### Задание 16

* По результатам работы с данными по оценкам за эссе студентов, поставленным двумя разными экспертами, были созданы два булевых массива `expert1` и `expert2`, в которых значение `True` означает оценку «удовлетворительно» и выше, а значение `False` – неудовлетворительно. 
* Всего было оценено 15 эссе, по 5 эссе на каждую из трёх тем.
* Определить, используя различные логические операторы (`|`, `&`, и проч.) и вспомогательные методы/функции, сколько студентов получат зачёт, если известно, что для этого необходимо получить оценку не ниже удовлетворительной у обоих экспертов.

In [19]:
expert1 = np.array([[True, False, False, True, True],
                   [False, True, False, False, True],
                   [True, True, True, False, False]])

expert2 = np.array([[True, False, False, False, True],
                   [False, False, False, False, False],
                   [True, False, True, False, False]])

In [20]:
marks = (expert1 == True) & (expert2 == True)
print(marks)
marks.sum()

[[ True False False False  True]
 [False False False False False]
 [ True False  True False False]]


4

### Задание 17

Дан массив `essay` с итоговыми оценками студентов за эссе из задачи 16:

In [21]:
# pass - сдал
# not pass - не сдал

essay = np.array([["pass", "not pass", "not pass", "not pass", "pass"],
        ["not pass", "not pass", "not pass", "not pass", "not pass"],
        ["pass", "not pass", "pass", "not pass", "not pass"]])

* Проверить ответ в предыдущей задаче, используя массив `essay`. 
* Решение должно быть представлено в виде кода, не в виде выводов в результате явного подсчёта элементов.

In [22]:
M = essay == "pass"
print(M)
np.array_equal(marks, M)

[[ True False False False  True]
 [False False False False False]
 [ True False  True False False]]


True

### Задание 18

Используя массивы `expert1` и `expert2` из задачи 16, определить согласованность двух экспертов, используя меру близости Жаккара, которая вычисляется следующим образом:

$$
J(A, B) = \frac{|A \cap B|}{|A| + |B| - |A \cap B|}
,$$ 

* где $A$ – первое множество, 
* $B$ – второе множество, 
* $A \cap B$ – пересечение множеств, т.е. их общие элементы. 
* Запись $|A|$ означает «количество элементов в множестве». 

В качестве множеств $A$ и $B$ в данной задаче выступают множества (группы) студентов, которые получили зачёт у первого и второго экспертов.

In [23]:
A = expert1.sum()
print(A)
B = expert2.sum()
print(B)
J = (expert1 & expert2).sum() / (A.sum() + B.sum() - (expert1 & expert2).sum())
J

8
4


0.5

### Задание 19

* Загрузить из файла `array_hw.npy` массив и сохранить его как `arr`. 
* Массив содержит объёмы продаж мороженого (в штуках) в 5 магазинах за одну неделю в июне (7 дней, с понедельника до воскресенья). 
* В заданиях 20-23 нужно работать с массивом `arr`.

In [25]:
arr = np.load("array_hw.npy") 
print(arr)

[[100  80  70  60 120]
 [ 65  55  20  50  60]
 [ 80  90  75  80  60]
 [ 45  60  70  20  40]
 [ 82  47  56  89  92]
 [115 120 113 106 107]
 [ 46  74  23  34  19]]


### Задание 20

* Если думать о массиве `arr` как о таблице, сейчас в таблице магазины идут по столбцам (1 магазин = 1 столбец, всего 5), а дни – по строкам (1 день = 1 строка, всего 7). 
* Преобразовать массив `arr` таким образом, чтобы по строкам шли магазины, а по столбцам – дни (1 строка = 1 магазин). 
* Сохранить изменения. 
* Проверить, что форма массива изменилась.

In [26]:
arr_T = arr.transpose()
print(arr_T)
print(arr.shape)
print(arr_T.shape)

[[100  65  80  45  82 115  46]
 [ 80  55  90  60  47 120  74]
 [ 70  20  75  70  56 113  23]
 [ 60  50  80  20  89 106  34]
 [120  60  60  40  92 107  19]]
(7, 5)
(5, 7)


### Задание 21

* Давайте представим, что информация по продажам обновилась: оказалось, что пятый магазин в воскресенье продал не 19 порций мороженого, а 25, и второй магазин продал во вторник не 55 порций, а 65. 
* Изменить массив `arr` в соответствии с этой информацией.

In [27]:
arr_T[4][6] = 25
arr_T[1][1] = 65
print(arr_T)

[[100  65  80  45  82 115  46]
 [ 80  65  90  60  47 120  74]
 [ 70  20  75  70  56 113  23]
 [ 60  50  80  20  89 106  34]
 [120  60  60  40  92 107  25]]


### Задание 22

Посчитать суммарный объём продаж мороженого по всем магазинам.

In [28]:
np.sum(arr_T)

2439

### Задание 23

* Выгрузить обновлённый массив `arr` в txt-файл. 
* Сам txt-файл загружать в систему не нужно, только написать соответствующий код в ipynb-файл.

In [29]:
np.savetxt("arr_T.txt", arr_T)

### Задание 24

* Дан массив `income`, содержащий значения прибыли магазина в тысячах на начало, середину и конец года, за четыре года подряд (значения никак не сгруппированы, можно считать, что они так выгрузились из файла). 
* Изменить форму массива так, чтобы значения были сгруппированы по три значения в каждом списке внутри массива (прибыль на начало, середину и конец года).

In [30]:
income = np.array([1000, 2000, 3500, 
                   2500, 1500, 3800, 
                   1200, 9000, 12000,
                   4500, 6700, 11000])

In [31]:
income2 = income.reshape(4, 3)
print(income2)

[[ 1000  2000  3500]
 [ 2500  1500  3800]
 [ 1200  9000 12000]
 [ 4500  6700 11000]]


### Задание 25

* Создать список `turnout` (*list*, не массив), содержащий следующие значения явки на избирательные участки в процентах:

23.56, 45.78, 34.92, 57.34, 56.55, 67.23.

* Создать, используя списковые включения и встроенные, не из `NumPy`, функции для округления, новый список `turnout_r`, который состоит из округлённых до первого знака после запятой значений явки из `turnout`.

In [32]:
turnout = [23.56, 45.78, 34.92, 57.34, 56.55, 67.23]
turnout = [round(i, 1) for i in turnout]
turnout

[23.6, 45.8, 34.9, 57.3, 56.5, 67.2]

### Задание 26

* Выполнить те же операции, что и в предыдущей задаче, но с использованием массивов и функций `NumPy`. 
* Другими словами, создать массив `turnout` и на его основе создать массив `turnout_r` с округлёнными до первого знака значениями явки.

In [33]:
turnout = np.array([23.56, 45.78, 34.92, 57.34, 56.55, 67.23])
print(turnout)
np.round(turnout, 1)

[23.56 45.78 34.92 57.34 56.55 67.23]


array([23.6, 45.8, 34.9, 57.3, 56.6, 67.2])

### Задание 27

* Зайдите на [страницу](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D0%B6%D0%B4%D1%83%D0%BD%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D1%8B%D0%B9_%D0%B8%D0%BD%D0%B4%D0%B5%D0%BA%D1%81_%D1%81%D1%87%D0%B0%D1%81%D1%82%D1%8C%D1%8F) Википедии, посвящённую Международному индексу счастья, выберите из таблицы **2012 Международный индекс счастья** любые 5 стран и любые 3 показателя и создайте структурированный массив `happy`, такой, в котором есть поле «название страны» и поля для трёх выбранных показателей. 
* Выберите подходящий тип для каждого поля (показателя) в массиве и учтите это при создание структурированного массива. 
* Выведите полученный массив на экран.

In [34]:
happy = np.array([('Индия', 5.0, 65.4, 0.9), ('Вьетнам', 5.8, 75.2, 1.4), ('Ямайка', 6.2, 73.1, 1.7),
                 ('Куба', 5.4, 79.1, 1.9), ('Япония', 6.1, 83.4, 4.2)], 
                dtype = [('Название страны', 'U10'), ('Удовлетворенность жизнью', float),
                         ('Ожидаемая продолжительность жизни', float), ('Экологический след', float)])
happy

array([('Индия', 5. , 65.4, 0.9), ('Вьетнам', 5.8, 75.2, 1.4),
       ('Ямайка', 6.2, 73.1, 1.7), ('Куба', 5.4, 79.1, 1.9),
       ('Япония', 6.1, 83.4, 4.2)],
      dtype=[('Название страны', '<U10'), ('Удовлетворенность жизнью', '<f8'), ('Ожидаемая продолжительность жизни', '<f8'), ('Экологический след', '<f8')])

### Задание 28

Сконвертируйте полученный в предыдущей задаче структурированный массив в обычный список и выведите на экран его второй элемент.

In [35]:
print(happy.ravel())
print(happy.ndim)
happy[1]

[('Индия', 5. , 65.4, 0.9) ('Вьетнам', 5.8, 75.2, 1.4)
 ('Ямайка', 6.2, 73.1, 1.7) ('Куба', 5.4, 79.1, 1.9)
 ('Япония', 6.1, 83.4, 4.2)]
1


('Вьетнам', 5.8, 75.2, 1.4)

### Задание 29

* Написать функцию `build_array()`, которая принимает на вход размерность квадратной матрицы (двумерного массива, в котором число строк и число столбцов совпадают) и создаёт единичную матрицу `E` (массив) соответствующей размерности. 
* Использовать готовую функцию `np.eye()` нельзя, можно использовать циклы и условные конструкции.

**Пример:**

Ввод:

    build_array(4)

Вывод:

    array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
def build_array(n):  # функция принимает на вход число n и выводит на экран единичную матрицу размера n
   
    square_matrix = np.zeros((n, n))
    
    for row in range(0, n):
        for col in range(0, n):
            if row == col:
                square_matrix[row][col] = 1
                
    return square_matrix
            
build_array(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Задание 30

Напишите функцию `my_reshape()`, которая принимает на вход массив и его новую размерность (пару чисел), и:

* если указанные измерения корректны, то возвращает массив новой размерности;
* если указанные измерения некорректны, то возвращает пустой массив (пример: из массива 2×5 нельзя сделать новый массив 4×3, потому что в старом массиве 10 элементов, а в новом – 12).

**Пример:**

Ввод:

    A = np.array([[2, 4, 6], 
            [4, 8, 10]])

    my_reshape(A, 6, 1)

Вывод:

    array([[2], 
       [4], 
       [6], 
       [4], 
       [8],
       [10]])

Ввод:

    A = np.array([[2, 4, 6], 
            [4, 8, 10]])

    my_reshape(A, 4, 2)

Вывод:

    array([])

**Примечание:** результаты в выводе могут визуально отличаться (выводиться без переносов по строкам, с указанием типа данных), это нормально, примеры модифицированы для читаемости.

In [42]:
# Вариант 1:

def my_reshape(array, p1, p2):
    
    if p1 * p2 == array.size:
        array = array.ravel()

        count = 0
        my_list = np.zeros((p1, p2))
        for i in range(p1):
            for j in range(p2):
                my_list[i][j] = array[count]
                count += 1
        print(my_list.astype(int))
        print(type(my_list))    # Проверяем, что вывелся массив, а не список  
        
    else:
        return np.array([])
    
    
A = np.array([[2, 4, 6], 
        [4, 8, 10]])

my_reshape(A, 6, 1)
my_reshape(A, 4, 2)

[[ 2]
 [ 4]
 [ 6]
 [ 4]
 [ 8]
 [10]]
<class 'numpy.ndarray'>


array([], dtype=float64)

In [40]:
# Вариант 2:

def my_reshape(name_of_array, row, colown):
    
    if name_of_array.size == row * colown:
        return name_of_array.reshape(row, colown)
    else:
        return np.array([])
    
A = np.array([[2, 4, 6], 
        [4, 8, 10]])

my_reshape(A, 6, 1)
# my_reshape(A, 4, 2)

array([[ 2],
       [ 4],
       [ 6],
       [ 4],
       [ 8],
       [10]])